name: Sysdig Pipeline Test

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Sysdig CLI Scanner
        run: |
          curl -sSL -o sysdig-cli-scanner \
            https://github.com/sysdiglabs/cli-scanner/releases/latest/download/sysdig-cli-scanner-linux-amd64
          chmod +x sysdig-cli-scanner

      - name: Run Sysdig Scan
        run: |
          SECURE_API_TOKEN=${{ secrets.SYSDIG_API_TOKEN }} ./sysdig-cli-scanner \
            --apiurl https://secure.sysdig.com \
            quay.io/scsk_ecchuuya/sysdigtest:v4
